{
 "title": "Node View",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "job_id", "label": "job_id", "query": { "query": "label_values(job_id)" } },
   { "name": "cpu_id", "label": "CPU", "query": { "query": "label_values(cpu_id)" } },
   { "name": "numa_domain", "label": "NUMA Node", "query": { "query": "label_values(numa_domain)" } }
  ]
 },
 "panels": [
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_cpu_util{job_id=~\"$job_id\",instance=~\"$instance\", cpu_id=~\"$cpu_id\", numa_domain=~\"$numa_domain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_cpu_frequency{job_id=~\"$job_id\",instance=~\"$instance\", cpu_id=~\"$cpu_id\", numa_domain=~\"$numa_domain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "User Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_cpu_times_user{job_id=~\"$job_id\",instance=~\"$instance\", cpu_id=~\"$cpu_id\", numa_domain=~\"$numa_domain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "node_cpu_times_system{job_id=~\"$job_id\",instance=~\"$instance\", cpu_id=~\"$cpu_id\", numa_domain=~\"$numa_domain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "node_cpu_times_idle{job_id=~\"$job_id\",instance=~\"$instance\", cpu_id=~\"$cpu_id\", numa_domain=~\"$numa_domain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "node_cpu_times_iowait{job_id=~\"$job_id\",instance=~\"$instance\", cpu_id=~\"$cpu_id\", numa_domain=~\"$numa_domain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_mem_util{job_id=~\"$job_id\",instance=~\"$instance\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "node_mem_available{job_id=~\"$job_id\", instance=~\"$instance\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  }
 ]
}