{
 "title": "Cluster View",
 "description": "Provides overview of cluster GPU and IB metrics ",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_id", "label": "Job ID", "query": { "query": "label_values(job_id)" } },
   {
    "name": "Operation",
    "query": "Average : 1, Minimum : 2,  Maximum : 3"
   }
  ]
 },
 "panels": [
  { "title": "GPU Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (dcgm_gpu_utilization{job_id=~\"$job_id\"}))  *  ($Operation== bool 1)  + (min by(instance) (dcgm_gpu_utilization{job_id=~\"$job_id\"}))  *  ($Operation== bool 2)  + (max by(instance) (dcgm_gpu_utilization{job_id=~\"$job_id\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Copy Utilization",
   "type": "timeseries",
   "description": "Average of VM GPU device Memory utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (dcgm_mem_copy_utilization{job_id=~\"$job_id\"}))  *  ($Operation== bool 1)  + (min by(instance) (dcgm_mem_copy_utilization{job_id=~\"$job_id\"}))  *  ($Operation== bool 2)  + (max by(instance) (dcgm_mem_copy_utilization{job_id=~\"$job_id\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SM Clock ",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device SM Clock",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(avg by(instance) (dcgm_sm_clock{job_id=~\"$job_id\"}))  *  ($Operation== bool 1)  + (min by(instance) (dcgm_sm_clock{job_id=~\"$job_id\"}))  *  ($Operation== bool 2)  + (max by(instance) (dcgm_sm_clock{job_id=~\"$job_id\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Memory Clock",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(avg by(instance) (dcgm_memory_clock{job_id=~\"$job_id\"}))  *  ($Operation== bool 1)  + (min by(instance) (dcgm_memory_clock{job_id=~\"$job_id\"}))  *  ($Operation== bool 2)  + (max by(instance) (dcgm_memory_clock{job_id=~\"$job_id\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(avg by(instance) (dcgm_gpu_temp{job_id=~\"$job_id\"}))  *  ($Operation== bool 1)  + (min by(instance) (dcgm_gpu_temp{job_id=~\"$job_id\"}))  *  ($Operation== bool 2)  + (max by(instance) (dcgm_gpu_temp{job_id=~\"$job_id\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Memory Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(avg by(instance) (dcgm_memory_temp{job_id=~\"$job_id\"}))  *  ($Operation== bool 1)  + (min by(instance) (dcgm_memory_temp{job_id=~\"$job_id\"}))  *  ($Operation== bool 2)  + (max by(instance) (dcgm_memory_temp{job_id=~\"$job_id\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU Power",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(avg by(instance) (dcgm_power_usage{job_id=~\"$job_id\"}))  *  ($Operation== bool 1)  + (min by(instance) (dcgm_power_usage{job_id=~\"$job_id\"}))  *  ($Operation== bool 2)  + (max by(instance) (dcgm_power_usage{job_id=~\"$job_id\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Throttle Code",
   "type": "timeseries",
   "description": "Max aggregation ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(instance) (dcgm_current_clock_throttle_reasons{job_id=~\"$job_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "IB Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "IB TX Rate",
   "type": "timeseries",
   "description": "Selected Operation of IB TX Rate of VM's HCAs ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg by(instance) (ib_port_xmit_data{job_id=~\"$job_id\"}))  *  ($Operation== bool 1)  + (min by(instance) (ib_port_xmit_data{job_id=~\"$job_id\"}))  *  ($Operation== bool 2)  + (max by(instance) (ib_port_xmit_data{job_id=~\"$job_id\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IB RX Rate",
   "type": "timeseries",
   "description": "Selected Operation of IB RX Rate of VM's HCAs ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg by(instance) (ib_port_rcv_data{job_id=~\"$job_id\"}))  *  ($Operation== bool 1)  + (min by(instance) (ib_port_rcv_data{job_id=~\"$job_id\"}))  *  ($Operation== bool 2)  + (max by(instance) (ib_port_rcv_data{job_id=~\"$job_id\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}