{
 "title": "GPU Profiling Counters",
 "description": "DCGM_FI_PROF_* Counters",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job_id", "label": "Job ID", "query": { "query": "label_values(job_id)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({ job_id=~\"$job_id\"}, instance)"
    }
   },
   { "name": "gpu_id", "label": "GPU", "query": { "query": "label_values(gpu_id)" } }
  ]
 },
 "panels": [
  { "title": "Streaming Multiprocessor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SM Active",
   "type": "graph",
   "description": "The fraction of time at least one warp was active on a multiprocessor, averaged over all multiprocessors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_sm_active{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "SM Occupancy",
   "type": "graph",
   "description": "The fraction of resident warps on a multiprocessor, relative to the maximum number of concurrent warps supported on a multiprocessor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_sm_occupancy{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Tensor Active",
   "type": "graph",
   "description": "The fraction of cycles the tensor (HMMA / IMMA) pipe was active",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_tensor_active{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "FP64 Active",
   "type": "graph",
   "description": "The fraction of cycles the FP64 (double precision) pipe was active",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_fp64_active{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "FP32 Active",
   "type": "graph",
   "description": "The fraction of cycles the FMA (FP32 (single precision), and integer) pipe was active",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_fp32_active{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "FP16 Active",
   "type": "graph",
   "description": "The fraction of cycles the FP16 (half precision) pipe was active",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_fp16_active{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "DRAM Active",
   "type": "graph",
   "description": "The fraction of cycles where data was sent to or received from device memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_dram_active{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "NVLink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "NVLink TX Rate",
   "type": "graph",
   "description": "The rate of data transmitted over NVLink, not including protocol headers, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "dcgm_nvlink_tx_bytes{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "NVLink RX Rate",
   "type": "graph",
   "description": "The rate of data received over NVLink, not including protocol headers, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "dcgm_nvlink_rx_bytes{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "PCIe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "PCIe TX Rate",
   "type": "graph",
   "description": "The rate of data transmitted over the PCIe bus, including both protocol headers and data payloads, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "dcgm_pcie_tx_bytes{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "PCIe RX Rate",
   "type": "graph",
   "description": "The rate of data received over the PCIe bus, including both protocol headers and data payloads, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "dcgm_pcie_rx_bytes{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  }
 ]
}