{
 "title": "GPU Device Counters",
 "description": "DCGM_FI_DEV_* Counters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_id", "label": "Job ID", "query": { "query": "label_values(job_id)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({ job_id=~\"$job_id\"}, instance)"
    }
   },
   { "name": "gpu_id", "label": "GPU", "query": { "query": "label_values(gpu_id)" } }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "description": "GPU utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Copy Utilization",
   "type": "graph",
   "description": "Memory utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "SM Clock",
   "type": "graph",
   "description": "SM clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "yaxes": [
    { "format": "MHz" }
   ],
   "targets": [
    {
     "expr": "dcgm_sm_clock{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "graph",
   "description": "Memory clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "yaxes": [
    { "format": "MHz" }
   ],
   "targets": [
    {
     "expr": "dcgm_memory_clock{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "description": "GPU temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_temp{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "graph",
   "description": "Memory temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dcgm_memory_temp{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Power Usage",
   "type": "graph",
   "description": "Power usage (in W)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "dcgm_power_usage{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption",
   "type": "graph",
   "description": "Total energy consumption since boot (in mJ)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "joule" }
   ],
   "targets": [
    {
     "expr": "dcgm_total_energy_consumption{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"} / 10^3",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "ECC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "SBE Volatile ECC Errors",
   "type": "graph",
   "description": "Total number of single-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_ecc_sbe_volatile_total{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "DBE Volatile ECC Errors",
   "type": "graph",
   "description": "Total number of double-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_ecc_dbe_volatile_total{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "SBE Persistent ECC Errors",
   "type": "graph",
   "description": "Total number of single-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_ecc_sbe_aggregate_total{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "DBE Persistent ECC Errors",
   "type": "graph",
   "description": "Total number of double-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_ecc_dbe_aggregate_total{job_id=~\"$job_id\",instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  }
 ]
}