{
 "title": "Node View",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_id", "label": "job_id", "query": { "query": "label_values(job_id)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job_id=~\"$job_id\"}, instance)"
    }
   },
   { "name": "numa_domain", "label": "NUMA Node", "query": { "query": "label_values(numa_domain)" } },
   {
    "name": "cpu_id",
    "label": "CPU",
    "query": {
     "query": "label_values({numa_domain=~\"$numa_domain\"}, cpu_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "description": "CPU Utilization",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_cpu_util{job_id=~\"$job_id\",instance=~\"$instance\", cpu_id=~\"$cpu_id\", numa_domain=~\"$numa_domain\"}",
       "legendFormat": "CPU {{cpu_id}}"
      }
     ]
    },
    {
     "title": "CPU Clock",
     "type": "timeseries",
     "description": "CPU Clock Speed",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "MHz" } },
     "targets": [
      {
       "expr": "node_cpu_frequency{job_id=~\"$job_id\",instance=~\"$instance\", cpu_id=~\"$cpu_id\", numa_domain=~\"$numa_domain\"}",
       "legendFormat": "CPU {{cpu_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "description": "Memory Utilization",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_mem_util{job_id=~\"$job_id\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "timeseries",
     "description": "Available memory",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "node_mem_available{job_id=~\"$job_id\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet TX Rate",
     "type": "timeseries",
     "description": "TX Rate of VM's  Ethernet Interface",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node_net_tx{job_id=~\"$job_id\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ethernet RX Rate",
     "type": "timeseries",
     "description": "RX Rate of VM's  Ethernet Interface",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node_net_rx{job_id=~\"$job_id\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}