global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    subscription: subscription_id
    cluster: cluster_name
    instance: instance_name
    physical_host: physical_host_name
remote_write:
  - url: "ingestion_endpoint"
    azuread:
      managed_identity:
        client_id: identity_client_id
scrape_configs:
  - job_name: 'dcgm_exporter'
    static_configs:
      - targets:
        - moneo-worker-0:8000
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
  - job_name: 'net_exporter'
    static_configs:
      - targets:
        - moneo-worker-0:8001
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - moneo-worker-0:8002
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
