{
 "title": "Cluster Unified View (Experimental)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Operation",
    "query": "Average : 1, Minimum : 2,  Maximum : 3"
   },
   { "name": "Subscription", "label": "Subscription", "query": { "query": "label_values(up,subscription)" } },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(dcgm_gpu_utilization{subscription=\"$Subscription\"},cluster)"
    }
   },
   {
    "name": "JobId",
    "label": "Job Id",
    "query": {
     "query": "label_values(dcgm_gpu_utilization{cluster=~\"$Cluster\"},job_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (python_info{subscription=\"$Subscription\", cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Total Node in Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dcgm_gpu_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\", job_id=\"$JobId\", gpu_id=\"0\"})"
    }
   ]
  },
  {
   "title": "Average GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (\r\n    average_dcgm_gpu_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_dcgm_gpu_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_dcgm_gpu_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GPU Mem Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (\r\n    average_dcgm_mem_copy_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_dcgm_mem_copy_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_dcgm_mem_copy_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "IB Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "IB TX Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\r\n    average_ib_port_xmit_data{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_ib_port_xmit_data{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_ib_port_xmit_data{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IB RX Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\r\n    average_ib_port_rcv_data{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_ib_port_rcv_data{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_ib_port_rcv_data{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n    average_dcgm_gpu_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_dcgm_gpu_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_dcgm_gpu_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n    average_dcgm_mem_copy_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_dcgm_mem_copy_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_dcgm_mem_copy_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "SM Clock",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device SM Clock",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(\r\n    average_dcgm_sm_clock{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_dcgm_sm_clock{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_dcgm_sm_clock{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Memory Clock",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(\r\n    average_dcgm_memory_clock{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_dcgm_memory_clock{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_dcgm_memory_clock{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(\r\n  average_dcgm_gpu_temp{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n  min_dcgm_gpu_temp{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n  max_dcgm_gpu_temp{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mem Temperature",
   "type": "timeseries",
   "description": "Memory temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(\r\n    average_dcgm_memory_temp{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_dcgm_memory_temp{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_dcgm_memory_temp{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU Power",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(\r\n    average_dcgm_power_usage{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\n    min_dcgm_power_usage{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\n    max_dcgm_power_usage{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n)",
     "legendFormat": "{{instance}}:{{gpu_id}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption",
   "type": "timeseries",
   "description": "Total energy consumption since boot (in mJ)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "average_dcgm_total_energy_consumption{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 1) +\r\nmin_dcgm_total_energy_consumption{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 2) +\r\nmax_dcgm_total_energy_consumption{subscription=\"$Subscription\", cluster=\"$Cluster\",job_id=~\"$JobId\"} * ($Operation== bool 3)\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "IB Port Down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "IB Port Down",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "ib_port_physical_state{subscription=\"$Subscription\", cluster=\"$Cluster\", job_id=~\"$JobId\"} == 0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Instance to Host Mapping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM to Physical Host Map",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "dcgm_gpu_temp{subscription=\"$Subscription\", cluster=\"$Cluster\",gpu_id=\"0\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}