{
 "title": "Network View",
 "tags": [ "Moneo" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "Subscription",
    "query": {
     "query": "label_values(ib_port_physical_state, subscription)"
    }
   },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(ib_port_physical_state{subscription=~\"$Subscription\"}, cluster)"
    }
   },
   {
    "name": "JobId",
    "label": "Job Id",
    "query": {
     "query": "label_values(ib_port_physical_state{cluster=\"$Cluster\"},job_id)"
    }
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ib_port_physical_state{cluster=\"$Cluster\", job_id=\"$JobId\"},instance)"
    }
   },
   {
    "name": "IBPort",
    "label": "IBPort",
    "query": {
     "query": "label_values(ib_port_physical_state{instance=~\"$Instance\"}, ib_port)"
    }
   }
  ]
 },
 "panels": [
  { "title": "InifiniBand", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IB Link Status",
   "type": "timeseries",
   "description": "Indication of IB Link Flap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ib_port_physical_state{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", ib_port=~\"$IBPort\"}",
     "legendFormat": "{{instance}}:{{ib_port}}"
    }
   ]
  },
  {
   "title": "IB TX Rate",
   "type": "timeseries",
   "description": "The rate of data transmitted over InfiniBand.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "ib_port_xmit_data{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", ib_port=~\"$IBPort\"}",
     "legendFormat": "{{instance}}:{{ib_port}}"
    }
   ]
  },
  {
   "title": "IB RX Rate",
   "type": "timeseries",
   "description": "The rate of data transmitted over InfiniBand.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "ib_port_rcv_data{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", ib_port=~\"$IBPort\"}",
     "legendFormat": "{{instance}}:{{ib_port}}"
    }
   ]
  },
  {
   "title": "Port Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Port Xmit Discards",
     "type": "timeseries",
     "description": "Total number of outbound packets discarded by the port because the port is down or congested.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ib_port_xmit_discards{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", ib_port=~\"$IBPort\"}",
       "legendFormat": "{{instance}}:{{ib_port}}"
      }
     ]
    },
    {
     "title": "Port Xmit Constraint Errors",
     "type": "timeseries",
     "description": "Total number of packets not transmitted from the switch physical port.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ib_port_xmit_constraint_errors{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", ib_port=~\"$IBPort\"}",
       "legendFormat": "{{instance}}:{{ib_port}}"
      }
     ]
    },
    {
     "title": "Port Rcv Errors",
     "type": "timeseries",
     "description": "Total number of packets containing an error that were received on the port.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ib_port_rcv_errors{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", ib_port=~\"$IBPort\"}",
       "legendFormat": "{{instance}}:{{ib_port}}"
      }
     ]
    },
    {
     "title": "Port Rcv Constraint Errors",
     "type": "timeseries",
     "description": "Total number of packets received on the switch physical port that are discarded.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ib_port_rcv_constraint_errors{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", ib_port=~\"$IBPort\"}",
       "legendFormat": "{{instance}}:{{ib_port}}"
      }
     ]
    },
    {
     "title": "Link Flap",
     "type": "table",
     "description": "Indication of IB Link Flap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_link_flap{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\", ib_port=~\"$IBPort\"}",
       "legendFormat": "{{instance}}:{{ib_port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "VM Instance to Host Mapping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM to Physical Host Map",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "ib_port_rcv_errors{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\", ib_port=\"mlx5_ib0:1\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}