{
 "title": "Node View",
 "tags": [ "Moneo" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Subscription", "label": "Subscription", "query": { "query": "label_values(up,subscription)" } },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{subscription=\"$Subscription\"},cluster)"
    }
   },
   {
    "name": "JobId",
    "label": "Job Id",
    "query": {
     "query": "label_values(up{cluster=\"$Cluster\"},job_id)"
    }
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{cluster=\"$Cluster\", job_id=\"$JobId\"},instance)"
    }
   },
   {
    "name": "NUMA",
    "label": "NUMA",
    "query": {
     "query": "label_values(node_cpu_util{instance=~\"$Instance\"},numa_domain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "CPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_cpu_util{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\",numa_domain=~\"$NUMA\"}",
     "legendFormat": "{{instance}}:{{cpu_id}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "CPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_cpu_util{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", numa_domain=~\"$NUMA\"}",
     "legendFormat": "{{instance}}:{{cpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "description": "Memory Utilization",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_mem_util{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "description": "Memory Utilization",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_mem_util{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet TX Rate",
     "type": "timeseries",
     "description": "TX Rate of VM's  Ethernet Interface",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node_net_tx{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ethernet RX Rate",
     "type": "timeseries",
     "description": "RX Rate of VM's  Ethernet Interface",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node_net_rx{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "VM Instance to Host Mapping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "VM to Physical Host Map",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "node_mem_util{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}