{
 "title": "GPU Device Counters",
 "description": "RDC_FI_* Counters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "gpu_id", "label": "GPU", "query": { "query": "label_values(gpu_id)" } }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "description": "GPU utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rdc_gpu_util{instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "Memory utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rdc_gpu_memory_usage{instance=~\"$instance\", gpu_id=~\"$gpu_id\"}/rdc_gpu_memory_total{instance=~\"$instance\", gpu_id=~\"$gpu_id\"}*100",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GPU Clock",
   "type": "graph",
   "description": "GPU clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "yaxes": [
    { "format": "MHz" }
   ],
   "targets": [
    {
     "expr": "rdc_gpu_clock{instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "graph",
   "description": "Memory clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "yaxes": [
    { "format": "MHz" }
   ],
   "targets": [
    {
     "expr": "rdc_mem_clock{instance=~\"$instance\", gpu_id=~\"$gpu_id\"}/1000000",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "description": "GPU temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "rdc_gpu_temp{instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "graph",
   "description": "Memory temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "rdc_memory_temp{instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Power Usage",
   "type": "graph",
   "description": "Power usage (in W)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "rdc_power_usage{instance=~\"$instance\", gpu_id=~\"$gpu_id\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  }
 ]
}